version: '3.8'

services:
  seeker:
    build:
      context: .
      dockerfile: ./cmd/seeker/Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/handshakes
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      
volumes:
  db_volume:
    external: true
    name: handshakes_db
    
