version: '3.8'

services:
  gatekeeper:
    build:
      context: .
      dockerfile: ./cmd/gatekeeper/Dockerfile
    ports:
      - 8080:8080
  queue:
    build: 
      context: .
      dockerfile: ./cmd/queue/Dockerfile
    depends_on:
      - gatekeeper
  seeker:
    build: 
      context: .
      dockerfile: ./cmd/seeker/Dockerfile
    depends_on:
      - queue
